#!/bin/bash

# Allows us to read user input below, assigns stdin to keyboard
exec < /dev/tty
 
# Check if the user wants to deploy static files to gh-pages branch
read -p "Deploy to gh-pages (y/n)? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
  exit # End script if user does not want to deploy
fi
 
# deploy the _site directory to the gh-pages branch
git subtree push --prefix _site origin gh-pages
